---
# hello-kubernetes.custom-message.yaml
apiVersion: v1
kind: Service
metadata:
  name: service-hello-world-02
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-world-02
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-02
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: hello-world-02
  template:
    metadata:
      labels:
        app: hello-world-02
    spec:
      containers:
      - name: hello-world-test
        image: harbor.frontedge.net/poc-caas/hello-kubernetes
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Pooc CaaS Kubernetes!
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poc-caas-02
spec:
  ingressClassName: nginx
  rules:
  - host: poc-caas-02.apps.k8s-001.frontedge.net
    http:
      paths:
      - backend:
          service:
            name: service-hello-world-02
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
---
